export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_ONE = 'FETCH_ONE';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const FETCH_ONE_ITEM = 'FETCH_ONE_ITEM';
export const FETCH_ALL_ITEM = 'FETCH_ALL_ITEM';
export const FETCH_ALL_ITEM_OBJECTS = 'FETCH_ALL_ITEM_OBJECTS';

export const FETCH_UNPURCHASED_ORDER = 'FETCH_UNPURCHASED_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ONE_ORDER = 'FETCH_ONE_ORDER';

export const CREATE_ORDER_ITEM = 'CREATE_ORDER_ITEM';
export const FETCH_ORDER_ITEMS = 'FETCH_ORDER_ITEMS';
export const UPDATE_ORDER_ITEM = 'UPDATE_ORDER_ITEM';
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';

export const CREATE_RATINGS = 'CREATE_RATINGS';
export const UPDATE_RATINGS = 'UPDATE_RATINGS';
export const DELETE_RATINGS = 'DELETE_RATINGS';
export const FETCH_ALL_RATINGS = 'FETCH_ALL_RATINGS';
